paths:
  dataset_path: "./data/raw_dataset"
  folder_A: "./data/folder_A"
  folder_B: "./data/folder_B"
  output_folder: "./data/output"

synthesis:
  num_images_to_generate: 2
  max_objects_per_image: 3
  min_object_area_ratio: 0.01
  max_object_area_ratio: 0.05
  rotation_range: [-30, 30]
  color_adjustment:
    brightness_range: [0.7, 1.3]
    contrast_range: [0.7, 1.3]
    saturation_range: [0.7, 1.3]